"""n8n-style session addresses. Generated bytes live in frozen slots under the run."""

from __future__ import annotations

import hashlib
import json
import secrets
import shutil
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from flowstep_runtime import FlowError, utc_now, write_json


def default_run_dir(codebase: Path, flow_id: str) -> Path:
    stamp = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
    short = secrets.token_hex(3)
    return Path(codebase).resolve() / "flowsteps" / "runs" / str(flow_id) / f"{stamp}_{short}"


def _kind_ext(kind: str) -> str:
    if kind == "image":
        return "png"
    if kind in {"json", "data"}:
        return "json"
    return "bin"


def slot_rel(step_id: str, *, kind: str = "file", item_index: int | None = None, attempt: int | None = None) -> str:
    ext = _kind_ext(kind)
    if item_index is not None:
        return f"milestones/{step_id}/items/{int(item_index):03d}/files/asset.{ext}"
    if attempt is not None:
        return f"milestones/{step_id}/work/attempts/{int(attempt):02d}/files/asset.{ext}"
    return f"milestones/{step_id}/out/files/asset.{ext}"


def ensure_session_tree(run_dir: Path, flow: dict[str, Any]) -> None:
    run_dir = Path(run_dir)
    run_dir.mkdir(parents=True, exist_ok=True)
    (run_dir / "record").mkdir(exist_ok=True)
    for step in flow.get("steps") or []:
        mid = str(step.get("id") or "")
        if not mid:
            continue
        (run_dir / "milestones" / mid / "in").mkdir(parents=True, exist_ok=True)
        (run_dir / "milestones" / mid / "work" / "attempts").mkdir(parents=True, exist_ok=True)
        (run_dir / "milestones" / mid / "out" / "files").mkdir(parents=True, exist_ok=True)
        if str(step.get("loop") or "none") == "for":
            (run_dir / "milestones" / mid / "items").mkdir(parents=True, exist_ok=True)
    manifest_path = run_dir / "manifest.json"
    if not manifest_path.is_file():
        write_json(
            manifest_path,
            {
                "schema": "m8m_run_manifest_v1",
                "flow_id": flow.get("flow_id"),
                "run_id": run_dir.name,
                "created_at": utc_now(),
                "slots": [],
            },
            overwrite=False,
        )


def address_for(
    run_dir: Path,
    step: dict[str, Any],
    *,
    item_index: int | None = None,
    attempt: int | None = None,
) -> dict[str, str]:
    kind = str(((step.get("asset") or {}).get("kind") if isinstance(step.get("asset"), dict) else "") or "file")
    slot = slot_rel(str(step["id"]), kind=kind, item_index=item_index, attempt=attempt)
    write_to = (Path(run_dir) / slot).resolve()
    write_to.parent.mkdir(parents=True, exist_ok=True)
    return {
        "run_dir": str(Path(run_dir).resolve()),
        "slot": slot.replace("\\", "/"),
        "write_to": str(write_to),
        "kind": kind,
    }


def attach_address(
    run_dir: Path,
    step: dict[str, Any],
    input_data: dict[str, Any],
    *,
    item_index: int | None = None,
    attempt: int | None = None,
) -> dict[str, Any]:
    payload = dict(input_data)
    payload["address"] = address_for(run_dir, step, item_index=item_index, attempt=attempt)
    return payload


def assert_in_run(run_dir: Path, value: str | Path) -> Path:
    path = Path(value)
    resolved = path.resolve() if path.is_absolute() else (Path(run_dir) / path).resolve()
    root = Path(run_dir).resolve()
    if resolved != root and root not in resolved.parents:
        raise FlowError(f"address leak: {value} is not inside the session run folder")
    return resolved


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(65536), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _first_file(value: Any) -> str | None:
    if isinstance(value, dict):
        raw = value.get("path")
        if isinstance(raw, str) and raw:
            return raw
        for child in value.values():
            found = _first_file(child)
            if found:
                return found
    if isinstance(value, str) and value:
        candidate = Path(value)
        if candidate.is_file():
            return value
    return None


def materialize_bytes_into_slot(
    run_dir: Path,
    step: dict[str, Any],
    result: dict[str, Any],
    *,
    item_index: int | None = None,
    attempt: int | None = None,
) -> dict[str, Any]:
    """Copy generated bytes into the frozen slot. Rewrite asset.path to the slot."""
    kind = str(((step.get("asset") or {}).get("kind") if isinstance(step.get("asset"), dict) else "") or "")
    if kind not in {"file", "image"}:
        return result
    addr = address_for(run_dir, step, item_index=item_index, attempt=attempt)
    dest = Path(addr["write_to"])
    dest.parent.mkdir(parents=True, exist_ok=True)
    src_raw = None
    asset = result.get("asset") if isinstance(result.get("asset"), dict) else {}
    if isinstance(asset.get("path"), str):
        src_raw = asset["path"]
    if not src_raw:
        src_raw = _first_file(result)
    if not src_raw:
        raise FlowError(f"{step['id']}: no file to place in session slot {addr['slot']}")
    src = Path(src_raw)
    if not src.is_file():
        src = Path(run_dir) / src_raw
    if not src.is_file():
        raise FlowError(f"{step['id']}: generated file not found: {src_raw}")
    if src.resolve() != dest.resolve():
        shutil.copy2(src, dest)
    digest = _sha256(dest)
    out = dict(result)
    out["asset"] = {
        "path": dest.as_posix(),
        "sha256": digest,
        "slot": addr["slot"],
    }
    assert_in_run(run_dir, dest)
    return out


def record_slot(run_dir: Path, step: dict[str, Any], result: dict[str, Any]) -> None:
    asset = result.get("asset") if isinstance(result.get("asset"), dict) else None
    if not asset or not asset.get("slot"):
        return
    path = Path(run_dir) / "manifest.json"
    if path.is_file():
        data = json.loads(path.read_text(encoding="utf-8"))
    else:
        data = {"schema": "m8m_run_manifest_v1", "run_id": Path(run_dir).name, "slots": []}
    slots = [item for item in (data.get("slots") or []) if item.get("path") != asset.get("slot")]
    slots.append(
        {
            "milestone": step["id"],
            "kind": ((step.get("asset") or {}).get("kind") if isinstance(step.get("asset"), dict) else None),
            "path": asset.get("slot"),
            "sha256": asset.get("sha256"),
        }
    )
    data["slots"] = slots
    data["updated_at"] = utc_now()
    write_json(path, data, overwrite=True)


def copy_envelope_to_slot(run_dir: Path, step: dict[str, Any], envelope_path: Path) -> None:
    dest = Path(run_dir) / "milestones" / step["id"] / "out" / "asset.json"
    dest.parent.mkdir(parents=True, exist_ok=True)
    if envelope_path.is_file() and dest.resolve() != envelope_path.resolve():
        shutil.copy2(envelope_path, dest)
