"""n8n-style session addresses. Generated bytes live in frozen slots under the run."""

from __future__ import annotations

import hashlib
import json
import secrets
import shutil
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from flowstep_runtime import FlowError, utc_now, write_json


def default_run_dir(codebase: Path, flow_id: str) -> Path:
    stamp = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
    short = secrets.token_hex(3)
    return Path(codebase).resolve() / "flowsteps" / "runs" / str(flow_id) / f"{stamp}_{short}"


def _kind_ext(kind: str) -> str:
    if kind == "image":
        return "png"
    if kind in {"json", "data"}:
        return "json"
    return "bin"


def slot_rel(step_id: str, *, kind: str = "file", item_index: int | None = None, attempt: int | None = None) -> str:
    ext = _kind_ext(kind)
    if item_index is not None:
        return f"milestones/{step_id}/items/{int(item_index):03d}/files/asset.{ext}"
    if attempt is not None:
        return f"milestones/{step_id}/work/attempts/{int(attempt):02d}/files/asset.{ext}"
    return f"milestones/{step_id}/out/files/asset.{ext}"


def ensure_session_tree(run_dir: Path, flow: dict[str, Any]) -> None:
    run_dir = Path(run_dir)
    run_dir.mkdir(parents=True, exist_ok=True)
    (run_dir / "record").mkdir(exist_ok=True)
    for step in flow.get("steps") or []:
        mid = str(step.get("id") or "")
        if not mid:
            continue
        (run_dir / "milestones" / mid / "in").mkdir(parents=True, exist_ok=True)
        (run_dir / "milestones" / mid / "work" / "attempts").mkdir(parents=True, exist_ok=True)
        (run_dir / "milestones" / mid / "out" / "files").mkdir(parents=True, exist_ok=True)
        if str(step.get("loop") or "none") == "for" or step.get("on_cycle") or step.get("cycle"):
            (run_dir / "milestones" / mid / "items").mkdir(parents=True, exist_ok=True)
        cycle = step.get("cycle") if isinstance(step.get("cycle"), dict) else None
        if cycle:
            cid = str(cycle.get("id") or step.get("on_cycle") or mid)
            (run_dir / "cycles" / cid).mkdir(parents=True, exist_ok=True)
    manifest_path = run_dir / "manifest.json"
    if not manifest_path.is_file():
        write_json(
            manifest_path,
            {
                "schema": "m8m_run_manifest_v1",
                "flow_id": flow.get("flow_id"),
                "run_id": run_dir.name,
                "created_at": utc_now(),
                "slots": [],
            },
            overwrite=False,
        )


def address_for(
    run_dir: Path,
    step: dict[str, Any],
    *,
    item_index: int | None = None,
    attempt: int | None = None,
) -> dict[str, str]:
    kind = str(((step.get("asset") or {}).get("kind") if isinstance(step.get("asset"), dict) else "") or "file")
    slot = slot_rel(str(step["id"]), kind=kind, item_index=item_index, attempt=attempt)
    write_to = (Path(run_dir) / slot).resolve()
    write_to.parent.mkdir(parents=True, exist_ok=True)
    return {
        "run_dir": str(Path(run_dir).resolve()),
        "slot": slot.replace("\\", "/"),
        "write_to": str(write_to),
        "kind": kind,
    }


def attach_address(
    run_dir: Path,
    step: dict[str, Any],
    input_data: dict[str, Any],
    *,
    item_index: int | None = None,
    attempt: int | None = None,
) -> dict[str, Any]:
    payload = dict(input_data)
    payload["address"] = address_for(run_dir, step, item_index=item_index, attempt=attempt)
    return payload


def assert_in_run(run_dir: Path, value: str | Path) -> Path:
    path = Path(value)
    resolved = path.resolve() if path.is_absolute() else (Path(run_dir) / path).resolve()
    root = Path(run_dir).resolve()
    if resolved != root and root not in resolved.parents:
        raise FlowError(f"address leak: {value} is not inside the session run folder")
    return resolved


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(65536), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _first_file(value: Any) -> str | None:
    if isinstance(value, dict):
        raw = value.get("path")
        if isinstance(raw, str) and raw:
            return raw
        for child in value.values():
            found = _first_file(child)
            if found:
                return found
    if isinstance(value, str) and value:
        candidate = Path(value)
        if candidate.is_file():
            return value
    return None


def materialize_bytes_into_slot(
    run_dir: Path,
    step: dict[str, Any],
    result: dict[str, Any],
    *,
    item_index: int | None = None,
    attempt: int | None = None,
) -> dict[str, Any]:
    """Copy generated bytes into the frozen slot. Rewrite asset.path to the slot."""
    kind = str(((step.get("asset") or {}).get("kind") if isinstance(step.get("asset"), dict) else "") or "")
    if kind not in {"file", "image"}:
        return result
    addr = address_for(run_dir, step, item_index=item_index, attempt=attempt)
    dest = Path(addr["write_to"])
    dest.parent.mkdir(parents=True, exist_ok=True)
    src_raw = None
    asset = result.get("asset") if isinstance(result.get("asset"), dict) else {}
    if isinstance(asset.get("path"), str):
        src_raw = asset["path"]
    if not src_raw:
        src_raw = _first_file(result)
    if not src_raw:
        raise FlowError(f"{step['id']}: no file to place in session slot {addr['slot']}")
    src = Path(src_raw)
    if not src.is_file():
        src = Path(run_dir) / src_raw
    if not src.is_file():
        raise FlowError(f"{step['id']}: generated file not found: {src_raw}")
    if src.resolve() != dest.resolve():
        shutil.copy2(src, dest)
    digest = _sha256(dest)
    out = dict(result)
    out["asset"] = {
        "path": dest.as_posix(),
        "sha256": digest,
        "slot": addr["slot"],
    }
    assert_in_run(run_dir, dest)
    return out


def record_slot(run_dir: Path, step: dict[str, Any], result: dict[str, Any]) -> None:
    asset = result.get("asset") if isinstance(result.get("asset"), dict) else None
    if not asset or not asset.get("slot"):
        return
    path = Path(run_dir) / "manifest.json"
    if path.is_file():
        data = json.loads(path.read_text(encoding="utf-8"))
    else:
        data = {"schema": "m8m_run_manifest_v1", "run_id": Path(run_dir).name, "slots": []}
    slots = [item for item in (data.get("slots") or []) if item.get("path") != asset.get("slot")]
    slots.append(
        {
            "milestone": step["id"],
            "kind": ((step.get("asset") or {}).get("kind") if isinstance(step.get("asset"), dict) else None),
            "path": asset.get("slot"),
            "sha256": asset.get("sha256"),
        }
    )
    data["slots"] = slots
    data["updated_at"] = utc_now()
    write_json(path, data, overwrite=True)


def record_skip(
    run_dir: Path,
    step: dict[str, Any],
    *,
    branch: str,
    reason: str,
) -> Path:
    dest = Path(run_dir) / "milestones" / step["id"] / "skipped.json"
    dest.parent.mkdir(parents=True, exist_ok=True)
    write_json(
        dest,
        {
            "schema": "m8m_skipped_v1",
            "milestone": step["id"],
            "skipped": True,
            "branch": branch,
            "reason": reason,
            "updated_at": utc_now(),
        },
        overwrite=True,
    )
    path = Path(run_dir) / "manifest.json"
    if path.is_file():
        data = json.loads(path.read_text(encoding="utf-8"))
    else:
        data = {"schema": "m8m_run_manifest_v1", "run_id": Path(run_dir).name, "slots": []}
    skipped = [item for item in (data.get("skipped") or []) if item.get("milestone") != step["id"]]
    skipped.append({"milestone": step["id"], "branch": branch, "reason": reason, "skipped": True})
    data["skipped"] = skipped
    data["updated_at"] = utc_now()
    write_json(path, data, overwrite=True)
    return dest


def copy_envelope_to_slot(run_dir: Path, step: dict[str, Any], envelope_path: Path) -> None:
    dest = Path(run_dir) / "milestones" / step["id"] / "out" / "asset.json"
    dest.parent.mkdir(parents=True, exist_ok=True)
    if envelope_path.is_file() and dest.resolve() != envelope_path.resolve():
        shutil.copy2(envelope_path, dest)


def cycle_id_of(step: dict[str, Any]) -> str:
    spec = step.get("cycle") if isinstance(step.get("cycle"), dict) else {}
    return str(spec.get("id") or step.get("on_cycle") or step.get("id") or "cycle")


def cycle_dir(run_dir: Path, cycle_id: str) -> Path:
    path = Path(run_dir) / "cycles" / cycle_id
    path.mkdir(parents=True, exist_ok=True)
    return path


def ledger_path(run_dir: Path, cycle_id: str) -> Path:
    return cycle_dir(run_dir, cycle_id) / "ledger.json"


def load_ledger(run_dir: Path, cycle_id: str) -> dict[str, Any] | None:
    path = ledger_path(run_dir, cycle_id)
    if not path.is_file():
        return None
    return json.loads(path.read_text(encoding="utf-8"))


def save_ledger(run_dir: Path, cycle_id: str, ledger: dict[str, Any]) -> Path:
    path = ledger_path(run_dir, cycle_id)
    ledger = dict(ledger)
    ledger.setdefault("schema", "m8m_cycle_ledger_v1")
    ledger["cycle"] = cycle_id
    ledger["updated_at"] = utc_now()
    write_json(path, ledger, overwrite=True)
    return path


def ledger_from_asset(asset: dict[str, Any], *, cycle_id: str, max_items: int = 8) -> dict[str, Any]:
    rows_raw = asset.get("rows")
    if not isinstance(rows_raw, list):
        for key in ("items", "pages", "images", "ledger"):
            candidate = asset.get(key)
            if isinstance(candidate, list):
                rows_raw = candidate
                break
    if not isinstance(rows_raw, list):
        rows_raw = []
    rows: list[dict[str, Any]] = []
    for index, raw in enumerate(rows_raw, start=1):
        if isinstance(raw, dict):
            row = dict(raw)
            row.setdefault("id", str(row.get("id") or f"{index:03d}"))
            row.setdefault("status", str(row.get("status") or "unfinished"))
        else:
            row = {"id": f"{index:03d}", "status": "unfinished", "value": raw}
        rows.append(row)
    if len(rows) > max_items:
        rows = rows[:max_items]
    return {
        "schema": "m8m_cycle_ledger_v1",
        "cycle": cycle_id,
        "max_items": max_items,
        "rows": rows,
    }


def first_unfinished(ledger: dict[str, Any] | None) -> dict[str, Any] | None:
    if not isinstance(ledger, dict):
        return None
    for row in ledger.get("rows") or []:
        if isinstance(row, dict) and str(row.get("status") or "unfinished") != "done":
            return row
    return None


def mark_row(ledger: dict[str, Any], row_id: str, *, status: str, slot: str | None = None) -> dict[str, Any]:
    out = dict(ledger)
    rows = []
    for row in out.get("rows") or []:
        if not isinstance(row, dict):
            rows.append(row)
            continue
        item = dict(row)
        if str(item.get("id") or "") == str(row_id):
            item["status"] = status
            if slot:
                item["slot"] = slot
        rows.append(item)
    out["rows"] = rows
    return out


def purge_cycle_live(run_dir: Path, steps: list[dict[str, Any]]) -> None:
    """Delete unfinished live residue. Never touch items/<done>/."""
    run_dir = Path(run_dir)
    for step in steps:
        mid = str(step.get("id") or "")
        if not mid:
            continue
        live = run_dir / "milestones" / mid / "out"
        work = run_dir / "milestones" / mid / "work"
        if live.exists():
            shutil.rmtree(live, ignore_errors=True)
        if work.exists():
            shutil.rmtree(work, ignore_errors=True)
        (run_dir / "milestones" / mid / "out" / "files").mkdir(parents=True, exist_ok=True)
        (run_dir / "milestones" / mid / "work" / "attempts").mkdir(parents=True, exist_ok=True)


def promote_cycle_round(
    run_dir: Path,
    flow: dict[str, Any],
    steps: list[dict[str, Any]],
    row_id: str,
) -> str:
    """Copy live out/ to items/<row>/ and keep it. Returns the slot prefix."""
    from flowstep_runtime import expected_artifact_path

    run_dir = Path(run_dir)
    prefix = ""
    for step in steps:
        mid = str(step.get("id") or "")
        dest = run_dir / "milestones" / mid / "items" / str(row_id)
        dest.mkdir(parents=True, exist_ok=True)
        live_out = run_dir / "milestones" / mid / "out"
        if live_out.exists():
            target = dest / "out"
            if target.exists():
                shutil.rmtree(target, ignore_errors=True)
            shutil.copytree(live_out, target)
        envelope = expected_artifact_path(run_dir, flow, step)
        if envelope.is_file():
            shutil.copy2(envelope, dest / "asset.json")
        prefix = f"milestones/{mid}/items/{row_id}"
    return prefix.replace("\\", "/")
